// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpxxuznyigvlndvzctzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdweHh1em55aWd2bG5kdnpjdHpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjI1NjMsImV4cCI6MjA2MDgzODU2M30.BIDh7Oiu42Jprz_I8ZIcdsztPTqjWY3q4IL9Q9B4bG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);